config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :states, only: [:index, :show];
  resources :facts, only: [:index, :show];

  root 'states#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fact.rb
class Fact < ApplicationRecord

    belongs_to :state
end

app/models/state.rb
class State < ApplicationRecord

    has_many :facts, :dependent => :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/facts_controller.rb
class FactsController < ApplicationController

    def show
        @states = State.all
        @fact = Fact.find_by_id(params[:id])
        @state = State.find_by_id(@fact.state_id)
    end


end

app/controllers/states_controller.rb
class StatesController < ApplicationController
    before_action :set_state, only: [:show]

    def show
        @states = State.all
        @facts = Fact.where(state_id: @state.id)
        render;
    end

    def index
        @states = State.all
    end

    private

    def set_state
        @state = State.find(params[:id])
        puts @state
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/facts/index.html.erb
<%= render 'partials/map'%>

app/views/facts/show.html.erb
<%= render 'partials/map'%>


<div class="stateinfo">
<label for="states">States: </label>
<div class="selectionBox">
    
    <select name="states" onchange="changeState(this.value)">
        <option value="" selected>Select</option>
        <% @states.each do |state| %>
            <option value="<%= state.id %>"><%= state.name %></option>
        <% end %>
    </select>
</div>
    </br>

    

    <div class="flagNameDiv">
        <img class="flag" src=<%= @state.flag_image %> height="100px">
        <h2><%= @state.name %></h2>
    </div>
    <p><%= @state.description %></p>
    <h5>State Capitol: <%= @state.capitol_name %></h5>
    <h5>State Population: <%= number_with_delimiter(@state.population, :delimiter => ',') %></h5>
    </br>
    <h3>Fun Facts (click to reveal location on map)</h3>
    <% @state.facts.each do |fact| %>
        <%= link_to fact.title, fact_path(fact) %>
        </br>
        </br>
    <% end %>
   
    
</div>

<script>
    var marker = L.marker([<%= @fact.lat %>, <%= @fact.lng %>]).addTo(mymap);
    var popup = marker.bindPopup('<b><%= @fact.details %></b>')
    popup.openPopup();

    function changeState(value) {
        window.location = "/states/" + value
    }

    if("<%= @state.name %>" == "Minnesota") {
        mymap.setView([46.2773, -94.265469], 7, {animation: false})
    } else {
        mymap.setView([39, -105.484862], 7, {animation: false})
    }

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StateFacts</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
  
    
    <script src="/US_states.js"></script>
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"
    integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A=="
    crossorigin=""/>
    <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"
    integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA=="
    crossorigin=""></script>
  
    
  </head>

  <body>
    <header>
      <h1>State Facts</h1>
    </header>
    <%= yield %>
    
    
  </body>
</html>

app/views/partials/_map.html.erb
<div id="mapid">



</div>



<script>
    var mymap = L.map('mapid').setView([37.0902, -95.7129], 5)
    
    const attribution =  '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors';
    const tileURL = 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png';
    const tiles = L.tileLayer(tileURL, {attribution})
    tiles.addTo(mymap)
    const geo = [US_states]
    L.geoJSON(geo, {
        style: function(feature) {
            switch (feature.properties.NAME) {
                case "Minnesota": return { color: '#90ee90'};
                case "Colorado": return { color: '#90ee90'};
                
            }
        }
    }).addTo(mymap)

   

</script>

app/views/states/index.html.erb
<%= render 'partials/map'%>

<div class="stateinfo">
    <label for="states">States: </label>
    <div class="selectionBox">
    <select name="states" onchange="window.location=this.value">
        <option value="" selected>Select</option>
    <% @states.each do |state| %>
        <option value="states/<%= state.id %>"><%= state.name %></option>
    <% end %>
    </select>
    </div>

    

</div>

app/views/states/map.html.erb
<div id="mapid">



</div>
<div class="stateinfo">hi</div>

<%# <script>
L.tileLayer('../assets/US_states.geojson', {
    attribution: 'as provided',
    maxZoom: 18,
    id: 'US_states',
    tileSize: 512,
    zoomOffset: -1,
}).addTo(map)
</script> %>
<script>
    const mymap = L.map('mapid').setView([37.0902, -95.7129], 4)
    
    const attribution =  '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors';
    const tileURL = 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png';
    const tiles = L.tileLayer(tileURL, {attribution})
    tiles.addTo(mymap)
</script>

app/views/states/show.html.erb
<%= render 'partials/map' %>

<div class="stateinfo">
<label for="states">States: </label>
<div class="selectionBox">
    <select name="states" onchange="window.location=this.value">
        <option value="" selected>Select</option>
    <% @states.each do |state| %>
        <option value="<%= state.id %>"><%= state.name %></option>
    <% end %>
    </select>
    </div>
    </br>

    

<div class="flagNameDiv">
    <img class="flag" src=<%= @state.flag_image %> height="100px">
    <h2><%= @state.name %></h2>
    </div>
    <p><%= @state.description %></p>
    <h5>State Capitol: <%= @state.capitol_name %></h5>
    <h5>State Population: <%= number_with_delimiter(@state.population, :delimiter => ',') %></h5>
    </br>
    <h3>Fun Facts (click to reveal location on map)</h3>
    <% @facts.each do |fact| %>
        <%= link_to fact.title, fact_path(fact) %>
        </br>
        </br>
    <% end %>
    </br>
    
</div>

<script>
    if("<%= @state.name %>" == "Minnesota") {
        mymap.setView([46.2773, -94.265469], 7, {animation: true})
    } else {
        mymap.setView([39, -105.484862], 7, {animation: true})
    }
    
</script>